/* empty css                      */import{S as f,N as g,P as h}from"./assets/vendor-BSBkFbx1.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();f.use([g,h]);function w(s){if(!s)return;s.destroy(!0,!0);const e=s.el;e==null||e.removeAttribute("style");const r=e==null?void 0:e.querySelector(".swiper-wrapper");r==null||r.removeAttribute("style"),e==null||e.querySelectorAll(".swiper-slide").forEach(l=>{l.removeAttribute("style")})}function m({rootSelector:s,prevEl:e,nextEl:r,paginationEl:l}){const t=document.querySelector(s);if(!t)return;const o=t.querySelector(".swiper");if(!o)return;let i=null;const n=window.matchMedia("(min-width: 1440px)"),c=()=>{i||(i=new f(o,{slidesPerView:1,spaceBetween:16,speed:450,loop:!1,grabCursor:!0,navigation:{prevEl:e,nextEl:r},pagination:{el:l,clickable:!0,type:"bullets"}}))},a=()=>{i&&(w(i),i=null)},d=()=>{n.matches?a():c()};d();const u=()=>d();n.addEventListener?n.addEventListener("change",u):n.addListener(u)}m({rootSelector:".gallery-swiper",prevEl:".gallery-prev",nextEl:".gallery-next",paginationEl:".gallery-pagination"});m({rootSelector:".soft-swiper",prevEl:".soft-prev",nextEl:".soft-next",paginationEl:".soft-pagination"});document.querySelectorAll(".faq-acc-el-trigger").forEach(s=>{s.addEventListener("click",()=>{const e=s.closest(".faq-acc-el"),r=e.querySelector(".faq-acc-el-descr-frame"),l=s.querySelector("svg"),t=e.classList.contains("open"),o=`
<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M3.3335 8H12.6668" stroke="white" stroke-opacity="0.25" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M8 3.3335V12.6668" stroke="white" stroke-opacity="0.25" stroke-linecap="round" stroke-linejoin="round" />
</svg>`,i=`
<svg width="23" height="23" viewBox="0 0 23 23" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M8.0139 8.01367L14.6136 14.6133" stroke="white" stroke-opacity="0.25" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M14.6135 8.01367L8.01385 14.6133" stroke="white" stroke-opacity="0.25" stroke-linecap="round" stroke-linejoin="round" />
</svg>`;t?(e.classList.remove("open"),r.style.maxHeight="0",l.outerHTML=o):(e.classList.add("open"),r.style.maxHeight=r.scrollHeight+"px",l.outerHTML=i)})});document.addEventListener("DOMContentLoaded",()=>{const s=document.querySelector(".menu-button"),e=s.querySelector(".icon"),r=document.querySelector(".modal"),l=document.querySelectorAll(".menu-list-item"),t=document.querySelector(".header");let o=!1;const i=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M4 6H20M4 12H20M4 18H20" stroke="#CAD5E2" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `,n=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M20 20L4 4M20 4L4 20" stroke="#A0B3C3" stroke-width="2" stroke-linecap="round" />
</svg>
    `;s.addEventListener("click",()=>{o=!o,e.innerHTML=o?n:i,o?c():a()}),l.forEach(u=>u.addEventListener("click",()=>{a(),e.innerHTML=i,o=!1})),window.addEventListener("scroll",d);function c(){r.style.display="block"}function a(){r.style.display="none"}function d(){t&&(window.scrollY>60?t.classList.add("header-scroll"):t.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function s(){const n=document.getElementById("site-header");return n?n.offsetHeight:0}function e(n){const c=document.getElementById(n);if(!c)return;const a=s(),d=c.getBoundingClientRect().top+window.pageYOffset-a;window.scrollTo({top:d,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(n=>{n.addEventListener("click",function(c){const a=this.getAttribute("href");if(!a)return;const[d,u]=a.split("#");if(!u)return;const p=window.location.pathname.split("/").pop();!(d===""||d==="./"||d===p||d==="./"+p)||!document.getElementById(u)||(c.preventDefault(),e(u),o(u))})});const l=document.querySelectorAll("section[id]"),t=document.querySelectorAll(".navigation-item");function o(n){t.forEach(a=>a.classList.remove("active"));const c=document.querySelector(`.navigation-item a[href*="#${n}"]`);c&&c.closest(".navigation-item").classList.add("active")}function i(){const n=window.pageYOffset+s()+100;l.forEach(c=>{const a=c.offsetTop,d=a+c.offsetHeight;n>=a&&n<d&&o(c.id)})}if(window.addEventListener("scroll",i),window.location.hash){const n=window.location.hash.substring(1);setTimeout(()=>{e(n),o(n)},300)}});document.addEventListener("DOMContentLoaded",function(){const s=document.getElementById("cookie-popup"),e=document.getElementById("accept-cookies"),r=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(s.style.display="block"),e.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),s.style.display="none"}),r.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),s.style.display="none"})});
//# sourceMappingURL=index.js.map
