/* empty css                      */import{S as u,N as g,P as y}from"./assets/vendor-BSBkFbx1.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();u.use([g,y]);function h(s){if(!s)return;s.destroy(!0,!0);const e=s.el;e==null||e.removeAttribute("style");const r=e==null?void 0:e.querySelector(".swiper-wrapper");r==null||r.removeAttribute("style"),e==null||e.querySelectorAll(".swiper-slide").forEach(i=>{i.removeAttribute("style")})}function p({rootSelector:s,prevEl:e,nextEl:r,paginationEl:i}){const t=document.querySelector(s);if(!t)return;const o=t.querySelector(".swiper");if(!o)return;let n=null;const l=window.matchMedia("(min-width: 1440px)"),d=()=>{n||(n=new u(o,{slidesPerView:1,spaceBetween:16,speed:450,loop:!1,grabCursor:!0,navigation:{prevEl:e,nextEl:r},pagination:{el:i,clickable:!0,type:"bullets"}}))},f=()=>{n&&(h(n),n=null)},c=()=>{l.matches?f():d()};c();const a=()=>c();l.addEventListener?l.addEventListener("change",a):l.addListener(a)}p({rootSelector:".gallery-swiper",prevEl:".gallery-prev",nextEl:".gallery-next",paginationEl:".gallery-pagination"});p({rootSelector:".soft-swiper",prevEl:".soft-prev",nextEl:".soft-next",paginationEl:".soft-pagination"});document.querySelectorAll(".faq-acc-el-trigger").forEach(s=>{s.addEventListener("click",()=>{const e=s.closest(".faq-acc-el"),r=e.querySelector(".faq-acc-el-descr-frame"),i=s.querySelector("svg"),t=e.classList.contains("open"),o=`
<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M3.3335 8H12.6668" stroke="white" stroke-opacity="0.25" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M8 3.3335V12.6668" stroke="white" stroke-opacity="0.25" stroke-linecap="round" stroke-linejoin="round" />
</svg>`,n=`
<svg width="23" height="23" viewBox="0 0 23 23" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M8.0139 8.01367L14.6136 14.6133" stroke="white" stroke-opacity="0.25" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M14.6135 8.01367L8.01385 14.6133" stroke="white" stroke-opacity="0.25" stroke-linecap="round" stroke-linejoin="round" />
</svg>`;t?(e.classList.remove("open"),r.style.maxHeight="0",i.outerHTML=o):(e.classList.add("open"),r.style.maxHeight=r.scrollHeight+"px",i.outerHTML=n)})});
//# sourceMappingURL=index.js.map
